# Generated by Django 4.1.3 on 2023-01-16 03:21

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tupc_id', models.IntegerField(blank=True, default=None, null=True, unique=True)),
                ('role', models.CharField(max_length=225)),
                ('year_course', models.CharField(max_length=20, null=True)),
                ('user_img', models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics/')),
                ('has_ongoing_transaction', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RpiIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToolQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_datetime', models.DateTimeField()),
                ('expected_borrow', models.DateTimeField()),
                ('expected_return', models.DateTimeField()),
                ('actual_borrowed', models.DateTimeField(default=None, null=True)),
                ('actual_returned', models.DateTimeField(default=None, null=True)),
                ('voided_on', models.DateTimeField(default=None, null=True)),
                ('status', models.CharField(max_length=25)),
                ('tupc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tupc_ids', to=settings.AUTH_USER_MODEL, to_field='tupc_id')),
                ('voided_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voided_bys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoidedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tks.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('tool_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tool_name', models.CharField(max_length=25)),
                ('tool_image', models.ImageField(upload_to='tool_images/')),
                ('storage', models.IntegerField()),
                ('layer', models.IntegerField()),
                ('status', models.CharField(default='AVAILABLE', max_length=25)),
                ('is_removed', models.BooleanField(default=False)),
                ('is_under_maintenance', models.BooleanField(default=False)),
                ('current_transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tks.transactions')),
                ('current_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='tupc_id')),
            ],
        ),
        migrations.CreateModel(
            name='ReservedTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=255)),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tks.transactions')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_status', models.CharField(max_length=25)),
                ('tool_borrowed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tks.tools')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tks.transactions')),
            ],
        ),
    ]
