# Generated by Django 4.1.3 on 2022-12-11 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='current_transacaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tks.transactions'),
        ),
    ]
