# Generated by Django 4.1.3 on 2023-01-19 02:52

from django.db import migrations, models
import storages.backends.sftpstorage


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, default=None, null=True, storage=storages.backends.sftpstorage.SFTPStorage(), upload_to='profile_pics/'),
        ),
    ]
