# Generated by Django 4.1.1 on 2022-09-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_course',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
