# Generated by Django 4.1.3 on 2023-01-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0002_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile_pics/'),
        ),
    ]
