# Generated by Django 4.1.3 on 2022-12-11 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0002_tools_current_transacaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='current_transacaction',
            new_name='current_transaction',
        ),
    ]
