# Generated by Django 4.1.3 on 2022-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0003_rename_current_transacaction_tools_current_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
