# Generated by Django 4.1.3 on 2022-12-11 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tks', '0004_alter_transactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
